# Generated by Django 5.2.1 on 2025-09-23 04:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='El número de cuenta debe tener exactamente 7 dígitos.', regex='^\\d{7}$')], verbose_name='Número de cuenta')),
                ('user_type', models.CharField(choices=[('student', 'Estudiante'), ('teacher', 'Maestro')], max_length=10, verbose_name='Tipo de usuario')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('career', models.CharField(blank=True, max_length=100, null=True, verbose_name='Carrera')),
                ('semester', models.IntegerField(blank=True, null=True, verbose_name='Semestre')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_attendance_percentage', models.FloatField(default=80.0)),
                ('can_manage_events', models.BooleanField(default=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
            ],
        ),
    ]
