# Generated by Django 5.2.6 on 2025-10-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auditlog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Assistant',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('student', 'Estudiante'), ('assistant', 'Asistente')], max_length=10, verbose_name='Tipo de usuario'),
        ),
    ]
