# Generated by Django 5.2.6 on 2025-10-01 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_teacher_assistant_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assistant',
            new_name='Asistente',
        ),
    ]
