# Generated by Django 5.2.6 on 2025-10-01 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_assistant_asistente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='career',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='semester',
        ),
    ]
