# Generated by Django 5.2.6 on 2025-10-02 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_userprofile_career_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('account_number', models.CharField(max_length=7, unique=True, verbose_name='Número de cuenta')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='approved', max_length=10, verbose_name='Estado de aprobación')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Motivo de rechazo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.userprofile', verbose_name='Aprobado por')),
            ],
            options={
                'verbose_name': 'Usuario Externo',
                'verbose_name_plural': 'Usuarios Externos',
                'ordering': ['-created_at'],
            },
        ),
    ]
