# Generated by Django 5.2.6 on 2025-10-04 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_asistente_minimum_attendance_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantProfile',
            fields=[
            ],
            options={
                'verbose_name': 'Asistente (Perfil)',
                'verbose_name_plural': 'Asistentes (Perfiles)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.userprofile',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.userprofile',),
        ),
        migrations.AlterModelOptions(
            name='asistente',
            options={'verbose_name': 'Permiso de Asistente', 'verbose_name_plural': 'Permisos de Asistentes'},
        ),
        migrations.AlterField(
            model_name='asistente',
            name='can_manage_events',
            field=models.BooleanField(default=True, verbose_name='Puede gestionar eventos'),
        ),
        migrations.AlterField(
            model_name='asistente',
            name='user_profile',
            field=models.OneToOneField(limit_choices_to={'user_type': 'assistant'}, on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile'),
        ),
    ]
