# Generated by Django 5.2.6 on 2025-10-01 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externaluser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='externaluser',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='externaluser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='externaluser',
            name='position',
        ),
        migrations.RemoveField(
            model_name='externaluser',
            name='reason',
        ),
    ]
