# Generated by Django 5.2.6 on 2025-10-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_externaluser_email_and_more'),
    ]

    operations = [
        # Renombrar temporary_id a account_number
        migrations.RenameField(
            model_name='externaluser',
            old_name='temporary_id',
            new_name='account_number',
        ),
        # Cambiar max_length de account_number de 20 a 7
        migrations.AlterField(
            model_name='externaluser',
            name='account_number',
            field=models.CharField(max_length=7, unique=True, verbose_name='Número de cuenta'),
        ),
        # Cambiar el default de status a 'approved'
        migrations.AlterField(
            model_name='externaluser',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='approved', max_length=10, verbose_name='Estado de aprobación'),
        ),
    ]
