# Generated by Django 5.2.6 on 2025-10-02 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_external_user'),
        ('events', '0004_auto_20251001_1400'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalUser',
        ),
    ]
