# Generated by Django 5.2.6 on 2025-10-01 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('authentication', '0003_rename_teacher_assistant_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='registered_by',
            field=models.ForeignKey(limit_choices_to={'user_type': 'assistant'}, on_delete=django.db.models.deletion.CASCADE, related_name='registered_attendances', to='authentication.userprofile', verbose_name='Registrado por'),
        ),
    ]
