# Generated by Django 5.2.6 on 2025-10-02 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_registered_by'),
        ('authentication', '0006_externaluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='external_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.externaluser', verbose_name='Usuario Externo'),
        ),
    ]
